### ISSUE TITLE
Which clip encoder is this?

### ISSUE THREAD

**Issue by jaymefosa** [guoqincode/AnimateAnyone-unofficial#17]
Magicanimate doesn't seem to have it in their pretrained directory. Is it the same as "laion/CLIP-ViT-B-32-laion2B-s34B-b79K" ?

**Comment by guoqincode** [comment]
I use the https://huggingface.co/openai/clip-vit-large-patch14

**Comment by jaymefosa** [comment]
roger that, thanks!
