### ISSUE TITLE
Why DWpose instead of densepose?

### ISSUE THREAD

**Issue by jaymefosa** [guoqincode/AnimateAnyone-unofficial#20]
Two papers report better results with the 'thicker' style of conditioning images:

https://arxiv.org/pdf/2308.03610.pdf (avatarverse)
https://arxiv.org/pdf/2311.16498.pdf (magicanimate)

Any reason you chose DWpose?

**Comment by sizhky2** [comment]
Perhaps one reason is that densepose restricts the boundaries of a face/figure thereby distorting the original image. E.g., Reference image of a skinny person + Dense pose of a normal person will distort the skinny person
