### ISSUE TITLE
About multi-gpu training

### ISSUE THREAD

**Issue by asdasdad738** [guoqincode/AnimateAnyone-unofficial#22]
It seems that DDP isn't used in train.py.

**Comment by ryancll** [comment]
I tried to wrap the trainable modules with DDP and it works for stage2 training. But I meet error when training referencenet in stage1 (during backward). Could anyone provide some instructions? @guoqincode

**Comment by guoqincode** [comment]
> I tried to wrap the trainable modules with DDP and it works for stage2 training. But I meet error when training referencenet in stage1 (during backward). Could anyone provide some instructions? @guoqincode

Maybe you can send your code to my email and I will check it when I have time.

**Comment by asdasdad738** [comment]
> I tried to wrap the trainable modules with DDP and it works for stage2 training. But I meet error when training referencenet in stage1 (during backward). Could anyone provide some instructions? @guoqincode

I just wrap the referencenet and pose guider with DDP directly, and it works.
