### ISSUE TITLE
what is the poseguider_checkpoint_path value?

### ISSUE THREAD

**Issue by linxiang4200** [guoqincode/AnimateAnyone-unofficial#25]
Hello, first of all thanks for your work.

I have some questions. During the second stage of training, in the train_stage_2.yaml file,
poseguider_checkpoint_path: ""
referencenet_checkpoint_path: ""
What should these two contents be? Should the model trained in the first stage be written in referencenet_checkpoint_path? 
Or something else, I hope to get your reply.

**Comment by guoqincode** [comment]
You can specify your trained model here, and modifying the code and config is very simple.

**Comment by linxiang4200** [comment]
Thank you for your reply. In which configuration should the model trained in the first stage be placed? What is the difference between poseguider_checkpoint_path and referencenet_checkpoint_path?
