### ISSUE TITLE
How big does the video dataset need to be for good results? 

### ISSUE THREAD

**Issue by sdexpanim** [guoqincode/AnimateAnyone-unofficial#3]

**Comment by guoqincode** [comment]
AnimateAnyone collects 5,000 high-quality videos, but they don't specify the details of the dataset, I think it's possible to start with a simple dataset like TikTok and gradually increase the data to train.

**Comment by sdexpanim** [comment]
thanks for the info!

**Comment by GuangtaoLyu** [comment]
> AnimateAnyone collects 5,000 high-quality videos, but they don't specify the details of the dataset, I think it's possible to start with a simple dataset like TikTok and gradually increase the data to train.

how to process my own video? can you share the process script?
