### ISSUE TITLE
About masks?

### ISSUE THREAD

**Issue by ireneMsm2020** [guoqincode/AnimateAnyone-unofficial#35]
In Tiktok dataset, there is a masks file。 Maybe the foreground is trained separately, Have you taken this into account?

**Comment by guoqincode** [comment]
This is a valid point, but it usually only works with mask labeled data like tiktok and tends to create a split between foreground and background.

**Comment by mymusise** [comment]
You're correct.
I had the DDP commented out while running, which led to the error mentioned. I attempted to run it on a single GPU with 48GB, but adding the DDP wrapper invariably causes an Out of Memory issue. 
I'm relatively new to distributed training, so I'd appreciate any insights into why this might be occurring.
