### ISSUE TITLE
The parameters of unet training are not used

### ISSUE THREAD

**Issue by mymusise** [guoqincode/AnimateAnyone-unofficial#39]
In `pipelines/animation_stage_1.py`, the parameters of unet  are  load from `config.pretrained_model_path`, does not load from `config.pretrained_unet_path`

**Comment by guoqincode** [comment]
Thank you very much. I modified animation_stage_1.py.

**Comment by SuSung-boy** [comment]
I have a question, Is unit trained? the code I remember unet's setting to (required(Fasle)), then whether load from config.pretrained_model_path or load from config.pretrained_unet_path, it should be no difference
