### ISSUE TITLE
about training memory optimization

### ISSUE THREAD

**Issue by zhangvia** [guoqincode/AnimateAnyone-unofficial#41]
In the README, you mentioned that you would optimize the training code using DeepSpeed and Accelerate. However, as far as I know, the DeepSpeed functionality integrated into the Accelerate library does not support multi-model training. Do you have any suggestions?

**Comment by zhangvia** [comment]
and From my test results, it appears that when resolution was set to 512, first-stage training cannot be conducted on a 40GB A100 even with a batch size of 1. Is this normal?

**Comment by guoqincode** [comment]
This is normal, 40G is too small for training.

**Comment by zhangvia** [comment]
> This is normal, 40G is too small for training.

what about the first question?
