### ISSUE TITLE
loss won't decrease

### ISSUE THREAD

**Issue by ShungJhon** [guoqincode/AnimateAnyone-unofficial#45]
<img width="806" alt="image" src="https://github.com/guoqincode/AnimateAnyone-unofficial/assets/63043669/95a50d67-e514-4d77-80e3-8b19c928a5a7">
Is it normal when training the stage 1, the loss doesn't decrease

**Comment by guoqincode** [comment]
To generate models (e.g., Diffusion models), evaluate the results not with loss but with visualization.
