### ISSUE TITLE
Have you noticed any issue during training related to the denoising timesteps?

### ISSUE THREAD

**Issue by jaymefosa** [guoqincode/AnimateAnyone-unofficial#5]
Per the title I've been a little perplexed to see that what was denoised well at 30 inference timesteps @ 60k training steps, requires 70 steps @ 100k training steps. 

My implementation is slightly different than yours so there could be quite a few things going on. Just curious if you noticed any similar behaviors since you're in the middle of training these days.

Thank you

**Comment by guoqincode** [comment]
I haven't had these problems yet

**Comment by SmileTAT** [comment]
Is it possible to give an inference script? I'm not sure about some of the details.

**Comment by guoqincode** [comment]
> Is it possible to give an inference script? I'm not sure about some of the details.

I've written a simple untested inference script that I can share with you if you want

**Comment by SmileTAT** [comment]
> > Is it possible to give an inference script? I'm not sure about some of the details.
> 
> I've written a simple untested inference script that I can share with you if you want

If possible, please send it to zju.shen2017@gmail.com.

I also wrote a test script with reference to magic-animate to test the results of the first training phase. The denoised image only has pose information and no texture information. I don’t know if it is normal.

After debugging, The update function of ReferenceNetAttention does not work in the first training stage because reader_attn_modules is [].

**Comment by Carlyx** [comment]
> > Is it possible to give an inference script? I'm not sure about some of the details.
> 
> I've written a simple untested inference script that I can share with you if you want

If possible, I also need the inference code for more details.   (yxpanglight@gmail.com)

**Comment by JiananZhao0224** [comment]
> > Is it possible to give an inference script? I'm not sure about some of the details.
> 
> I've written a simple untested inference script that I can share with you if you want

If possible, I also need the inference code for more details. Thanks a lot ! (popaslan@sina.com)

**Comment by 21-10-4** [comment]
If possible, I hope I can get one. Thanks a lot.（zhanzhan4399@gmail.com） 
@guoqincode

**Comment by goo2go** [comment]
（654227280@qq.com），test scripts，thanks

**Comment by ccyyatnet** [comment]
Can anybody share the infer code? THANKS a lot~ （1124015396@qq.com）
