### ISSUE TITLE
how to get the model's config.json？

### ISSUE THREAD

**Issue by ShungJhon** [guoqincode/AnimateAnyone-unofficial#55]
to animate the stage2 result, the code using a config.json for the pretrained model, how to get it?

**Comment by lbwang2006** [comment]
I think sd1.5 unet config.json is ok, BTW，Is your stage 1 training result is ok? please share your insight thx

**Comment by ShungJhon** [comment]
> I think sd1.5 unet config.json is ok, BTW，Is your stage 1 training result is ok? please share your insight thx

I'm using ubc dataset for the first stage, the result is a static video, I'm not sure if the result is correct, the output looks very blur. 
![grid](https://github.com/guoqincode/AnimateAnyone-unofficial/assets/63043669/b270aa2a-ccd2-4778-9090-f5ceeb4ac516)

**Comment by lbwang2006** [comment]
you can change a different pose compared with input images, to prove the pose condition is valid,
