### ISSUE TITLE
Getting brown background images

### ISSUE THREAD

**Issue by Bismuth209** [guoqincode/AnimateAnyone-unofficial#58]
<img width="1385" alt="image" src="https://github.com/guoqincode/AnimateAnyone-unofficial/assets/153806859/c52accf7-c1d9-4211-b756-c01878e1ef5a">

I trained for 30000 steps using `train_stage_1.yaml` What could the issue be?

**Comment by zhenzhiwang** [comment]
We also have such issues. Training more iterations in stage 1 could alleviate this issue. We still don't know how to solve this in stage 2.

**Comment by Bismuth209** [comment]
How many iterations would you recommend?
