### ISSUE TITLE
train 13000 step, texture is much different from reference image

### ISSUE THREAD

**Issue by tczuo** [guoqincode/AnimateAnyone-unofficial#63]
In first stage,  In oder to train model easy, we remove posenet, use VAE encoder instead（cat with noise like in-painting  SD).
Now it train 13000 step， texture is much different from reference image,  is this correct? or we just need to waiting for more steps?
![image](https://github.com/guoqincode/AnimateAnyone-unofficial/assets/9945763/b9727e75-6c95-44ac-98fd-2066630b3940)
![image](https://github.com/guoqincode/AnimateAnyone-unofficial/assets/9945763/550c89e7-574f-49ff-97b8-26660c096b58)

**Comment by guoqincode** [comment]
I don't think it's normal... It looks scary.

**Comment by tczuo** [comment]
> I don't think it's normal... It looks scary.
I just use your code, besides use VAE encoder instead.  Could you send me your pretrain weights, I really want to know why result is so bad, Thanks  a  lot. This is my e-mail    **tonyzuo1993@gmail.com**

**Comment by guoqincode** [comment]
I will release the pre-trained model as soon as possible, please be patient, it may not take a few days.

**Comment by tczuo** [comment]
> I will release the pre-trained model as soon as possible, please be patient, it may not take a few days.

OK, I train it use 512x768,  use r.clear(), w.clear(), can you give some advise for this bad result?  data, or code?

**Comment by guoqincode** [comment]
If it's a texture issue, I have two suggestions.
1. Train more steps
2. Check if unet is updated

**Comment by tczuo** [comment]
> If it's a texture issue, I have two suggestions.
> 
> 1. Train more steps
> 2. Check if unet is updated

Thank you ~

**Comment by sizhky** [comment]
> Check if unet is updated
Can you elaborate @guoqincode

**Comment by renrenzsbbb** [comment]
> > If it's a texture issue, I have two suggestions.
> > 
> > 1. Train more steps
> > 2. Check if unet is updated
> 
> Thank you ~

Can you fix it? If can, can you give some advices?
