### ISSUE TITLE
Seeing artefacts in generated images after 10000 steps

### ISSUE THREAD

**Issue by Bismuth209** [guoqincode/AnimateAnyone-unofficial#68]
<img width="852" alt="image" src="https://github.com/guoqincode/AnimateAnyone-unofficial/assets/153806859/ea135937-60d7-4084-8a80-15142259ee38">

Is this normal?

**Comment by guoqincode** [comment]
If in stage1, I think this is very abnormal.

**Comment by Bismuth209** [comment]
what do you think might be the issue? 
I'm directly using `train_hack.py` on UBC images

**Comment by guoqincode** [comment]
Maybe you can overfit the training on a few videos first.

**Comment by Bismuth209** [comment]
I'm getting same issues even on overfitting on a few images... like I trained for a few hours on 3 images and am still seeing same issues. is there any issue with the vae encoder decoder? I'm using `clip-vit-base-patch32` for clip and the normal vae from stable diffusion 1.5

**Comment by Bismuth209** [comment]
this is my config
https://github.com/Bismuth209/AnimateAnyone-unofficial/blob/main/configs/training/v2/v2.2.yaml

**Comment by guoqincode** [comment]
I'm sorry, I've never seen this before. I feel very awkward...

**Comment by Bismuth209** [comment]
I'm sorry but I'm not sure what you mean.
