### ISSUE TITLE
train stage 1 OOM

### ISSUE THREAD

**Issue by LeonJoe13** [guoqincode/AnimateAnyone-unofficial#69]
Thanks for your great effort in this wonderful work!
I have some questions about train stage 1, my env is V100 32G, torch 2.0.1, python 3.9.18
I set 
train_batch_size=1,   
sample_size:  16 # for 40G 256 
sample_stride: 4, 
sample_n_frames: 2 
mixed_precision_training: true 
enable_xformers_memory_efficient_attention: True in train_stage_1.yaml, 
I still got OOM,could you help me?

**Comment by guoqincode** [comment]
I tried your configuration and it requires 36G VRAM.

**Comment by guoqincode** [comment]
Maybe you can start by not training unet and only train uent after some training steps (pose and appearance are good)

**Comment by LeonJoe13** [comment]
> Maybe you can start by not training unet and only train uent after some training steps (pose and appearance are good)

thank you! I frezze referencenet and it works!

**Comment by wangxr1999** [comment]
How should it be modified？
