### ISSUE TITLE
motion_unet

### ISSUE THREAD

**Issue by xiyuedemo** [guoqincode/AnimateAnyone-unofficial#70]
When applying the model to the model, the problem does not appear, and the main branch is only placed in the position, so the problem is difficult.

 File "/data/zzy/demo/../models/unet.py", line 481, in from_pretrained_2d
    raise RuntimeError(f"{model_file} does not exist")
RuntimeError: /data/zzy/pretrained_models/motion_unet/sd15_mmv1.ckpt does not exist

**Comment by xiyuedemo** [comment]
> 什么是解决方案？

I am also very confused. There is no corresponding pre-trained model file. I want to preliminarily verify the effect. The author forced it to close it. It's puzzling, There is no solution now.

**Comment by G-force78** [comment]
Are you using this? https://huggingface.co/guoyww/animatediff/blob/main/mm_sd_v15.ckpt
