### ISSUE TITLE
model saving

### ISSUE THREAD

**Issue by Carlyx** [guoqincode/AnimateAnyone-unofficial#8]
Hi,  it seems that you train the 2D unet, referencenet, and poseguider during the **first** stage, 
but you don't save parameters of 2D unet.

**Comment by Carlyx** [comment]
You set unet.requires_grad_(False) in (https://github.com/guoqincode/AnimateAnyone-unofficial/blob/45ecbe2d8495c9663e213e0d7dd2df06ca5bcd33/train.py#L224C1-L224C1),
but the grad is set to True in the next few lines (https://github.com/guoqincode/AnimateAnyone-unofficial/blob/45ecbe2d8495c9663e213e0d7dd2df06ca5bcd33/train.py#L228). 
I print the grad and it shows True.

**Comment by guoqincode** [comment]
Sorry, I forgot to upload the latest config and train.py on github. . .
