### ISSUE TITLE
SparseCausalAttention2D

### ISSUE THREAD

**Issue by kecol** [guoqincode/AnimateAnyone-unofficial#9]
While reading the code I saw that the standard BasicTransformerBlock from diffusers has been replaced with a modified version that utilizes a new class called SparseCausalAttention2D for the attn1 layer. Could you specify where this class is defined? Or maybe, were you able to successfully train the model without using this class (replacing it with a different one)?

**Comment by guoqincode** [comment]
If you do not set unet_use_cross_frame_attention=True, this class will not be used. AnimateAnyone does not use cross frame attention.

**Comment by kecol** [comment]
Thank you @guoqincode for your quick answer. The AnimateAnyone paper stated that all self-attention layers were replaced with spatial attention layers. I initially thought this was in reference to the aforementioned change.
