### ISSUE TITLE
I use train_hack, why stage2  background is very bad?

### ISSUE THREAD

**Issue by VisionU** [guoqincode/AnimateAnyone-unofficial#95]
I train it use UBC fashion dataset， stage1 test result is right,  but  background of stage2 result is very abnormal, could  you give some advise, thanks !

Stage1: 

![3d133f09-383e-4eab-80c8-01aed5d45000](https://github.com/guoqincode/Open-AnimateAnyone/assets/9945763/c60ed89f-9898-48ea-a3df-5f4278fccc42)
![output](https://github.com/guoqincode/Open-AnimateAnyone/assets/9945763/54f28e9b-3670-4f18-b2c8-ee8079df5d91)

Stage2: 

https://github.com/guoqincode/Open-AnimateAnyone/assets/9945763/395ccf52-f8c8-4e44-8053-b5e7acb56d45

@zhenzhiwang @guoqincode @ailingzengzzz

**Comment by VisionU** [comment]
> 1. You can replace poseguider's 2d conv with resnet.InflatedConv3d
> 2. Notifying so many people makes no sense

Thanks for your help. OK, I understand~

**Comment by kings-rgb** [comment]
> > 1. You can replace poseguider's 2d conv with resnet.InflatedConv3d
> > 2. Notifying so many people makes no sense
> 
> Thanks for your help. OK, I understand~

Do you solve this question?

**Comment by VisionU** [comment]
> > > 1. You can replace poseguider's 2d conv with resnet.InflatedConv3d
> > > 2. Notifying so many people makes no sense
> > 
> > 
> > Thanks for your help. OK, I understand~
> 
> Do you solve this question?

NO, use zero terminal  snr can fix it

**Comment by newcherryberry** [comment]
@VisionU Hi, is there any way I can possibly contact you about your progress? Would really appreciate it as a CS student
